name: Block Kustomization in nn-id-dev cluster

on:
  push:
    branches:
      - master  # Mengubah dari main ke master
    paths:
      - 'flux/clusters/nn-id-dev/**'
  pull_request:
    branches:
      - master  # Mengubah dari main ke master
    paths:
      - 'flux/clusters/nn-id-dev/**'

jobs:
  block-kustomization-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to properly compare changes

      - name: Check for forbidden kustomization file in pull request
        if: github.event_name == 'pull_request'
        run: |
          # Menampilkan informasi debug
          echo "Event name: ${{ github.event_name }}"
          echo "Base ref: ${{ github.base_ref }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "Repository: ${{ github.repository }}"
          
          # Menggunakan metode alternatif untuk memeriksa file yang ditambahkan
          git fetch origin ${{ github.base_ref || 'master' }} --depth=1
          
          # List semua file yang diubah dalam PR
          echo "Modified files:"
          git diff --name-only origin/${{ github.base_ref || 'master' }}...HEAD
          
          if git diff --name-status origin/${{ github.base_ref || 'master' }}...HEAD | grep -iE "^A\s+flux/clusters/nn-id-dev/.*/?kustomization.*"; then
            echo "❌ Error: Adding a kustomization file in flux/clusters/nn-id-dev is not allowed."
            exit 1
          else
            echo "✅ No forbidden kustomization file detected."
          fi
      
      - name: Check for forbidden kustomization file in push
        if: github.event_name == 'push'
        run: |
          # For direct pushes, check the latest commit
          if git diff-tree --no-commit-id --name-status -r ${{ github.sha }} | grep -iE "^A\s+flux/clusters/nn-id-dev/.*/?kustomization.*"; then
            echo "❌ Error: Adding a kustomization file in flux/clusters/nn-id-dev is not allowed."
            exit 1
          else
            echo "✅ No forbidden kustomization file detected."
          fi